### ISSUE TITLE
DoorWindow version 2 support

### ISSUE THREAD

**Issue by tomcoonen** [Schnittcher/IPS-Shelly#20]
Do you accept a PR to add support for the DW2 sensor?

**Comment by tomcoonen** [comment]
To define the issue;

- Temperature support is missing
- Vibration support is missing
- Tilt support is missing
- When the `state` is `open` the `State` variable should be true, this is now inversed

**Comment by Schnittcher** [comment]
I've added this.

**Comment by tomcoonen** [comment]
@Schnittcher nice, did you also have a look a the reversed state boolean?
