### ISSUE TITLE
Shelly Pro 3EM not compatible

### ISSUE THREAD

**Issue by Buck1976** [Schnittcher/IPS-Shelly#23]
Shelly Pro 3EM is listed in instance configuration but not enabled to create as an object. 

![image](https://github.com/Schnittcher/IPS-Shelly/assets/146076137/7cf8ac9e-81b5-4113-9e8e-99bcde3cadb8)

**Comment by Schnittcher** [comment]
Please use the beta version of this module.
It should work there.

**Comment by Buck1976** [comment]
Thanks. It works :-)

**Comment by Buck1976** [comment]
Forgot to close ;-)
